name: Pearson-ML
channels:
  - intel
  - conda-forge
dependencies:
  - python=3.7
  - scikit-learn=0.22
  - hdbscan
  - pandas
  - numpy
  - matplotlib
  - jupyter
  - seaborn
  - pillow
  - graphviz
  - pygraphviz
  - pyamg
  - jupyterlab
